name: network_collection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - graph-tool
  - pandas
  #- jupyter
  - openpyxl
  - xlrd
  - requests
  - pip:
      - rarfile==4.0
      - unrar==0.4
