name: network_collection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - graph-tool
  - pandas
  - requests
  - tqdm
  - xlrd
  - pip 
  - pip:
      - rarfile==4.0
      - unrar==0.4
